#!/usr/bin/env node
/**
 * Splits a delta package.xml generated by sfdx-git-delta.
 *
 * - Writes a copy of package.xml WITHOUT the AiAuthoringBundle <types> block
 *   (those agents are handled by `sf agent publish`/`activate`, not metadata deploy).
 * - Prints the AiAuthoringBundle member names (one per line) to stdout so the
 *   shell can iterate and publish/activate each changed agent.
 *
 * Usage: node split-package.js <package.xml> <output-without-agents.xml>
 */
const fs = require("fs");

const [, , inPath, outPath] = process.argv;
if (!inPath || !outPath) {
  console.error("Usage: node split-package.js <in package.xml> <out package.xml>");
  process.exit(2);
}

const xml = fs.readFileSync(inPath, "utf8");

const typesRegex = /<types>[\s\S]*?<\/types>/g;
const agentMembers = [];

const remaining = xml.replace(typesRegex, (block) => {
  const nameMatch = block.match(/<name>([^<]+)<\/name>/);
  const typeName = nameMatch ? nameMatch[1].trim() : "";
  if (typeName === "AiAuthoringBundle") {
    const members = block.match(/<members>([^<]+)<\/members>/g) || [];
    for (const m of members) {
      const v = m.replace(/<\/?members>/g, "").trim();
      if (v) agentMembers.push(v);
    }
    return ""; // strip agent block from metadata package
  }
  return block;
});

// Clean up empty lines left by stripped blocks.
const cleaned = remaining.replace(/^\s*\n/gm, (l) => l).replace(/\n{3,}/g, "\n\n");

fs.writeFileSync(outPath, cleaned, "utf8");

// Emit agent api-names for the shell to consume.
for (const a of agentMembers) console.log(a);
